[package]
name = "labrador-ldpc"
version = "0.1.0"
authors = ["Adam Greig <adam@adamgreig.com>"]
description = "Encoders and decoders for LDPC error correcting codes"
keywords = ["ldpc", "ecc", "labrador"]
categories = ["embedded", "no-std"]
license = "MIT"

[profile.release]
debug=true
